CREATE TEXT SEARCH CONFIGURATION BUSCA (COPY = portuguese);
ALTER TEXT SEARCH CONFIGURATION BUSCA ALTER MAPPING FOR hword, hword_part, word WITH portuguese_stem;

CREATE TABLE IF NOT EXISTS PESSOAS (
    ID VARCHAR(36),
    APELIDO VARCHAR(32) CONSTRAINT ID_PK PRIMARY KEY,
    NOME VARCHAR(100),
    NASCIMENTO CHAR(10),
    STACK VARCHAR(1024),
    -- BUSCA TSVECTOR GENERATED ALWAYS AS (
    --     TO_TSVECTOR('BUSCA', NOME || ' ' || APELIDO || ' ' || STACK)
    -- ) STORED,
    BUSCA_TRGM TEXT GENERATED ALWAYS AS (
        LOWER(NOME) || LOWER(APELIDO) || LOWER(STACK)
    ) STORED
);

CREATE EXTENSION PG_TRGM;

-- CREATE INDEX CONCURRENTLY IF NOT EXISTS IDX_PESSOAS_ID ON PESSOAS USING HASH (ID);
-- CREATE INDEX CONCURRENTLY IF NOT EXISTS IDX_PESSOAS_BUSCA ON PESSOAS USING GIN (BUSCA);
CREATE INDEX CONCURRENTLY IF NOT EXISTS IDX_PESSOAS_BUSCA_TGRM ON PESSOAS USING GIST (BUSCA_TRGM GIST_TRGM_OPS);