CREATE TABLE IF NOT EXISTS PESSOAS (
  ID CHAR(32) CONSTRAINT ID_PK PRIMARY KEY,
  APELIDO VARCHAR(32),
  NOME VARCHAR(100),
  NASCIMENTO CHAR(10),
  STACK VARCHAR(1024),
  CONSTRAINT APELIDO_UNIQUE UNIQUE (apelido)
);